@props(['status', 'label' => null])

@php
    $value = $status instanceof BackedEnum ? $status->value : (string) $status;
    $key = strtoupper($value);
    $labels = [
        'DRAFT' => 'Draft',
        'UNDER_SPMU' => 'Under SPMU Review',
        'UNDER_GSU' => 'Legacy Review',
        'UNDER_VPAF' => 'Legacy Review',
        'PENDING' => 'Pending',
        'RECEIVED' => 'Pending Review',
        'RETURNED_FOR_REVISION' => 'Returned for Revision',
        'FINAL_APPROVED_AWAITING_DOWNLOAD' => 'Approved Letter Ready',
        'APPROVED_READY_FOR_RELEASE' => 'Ready for Release',
        'PREPARING_RELEASE' => 'Preparing for Release',
        'RETURN_PROCESSING' => 'Return Processing',
        'OBLIGATION_OPEN' => 'Outstanding Obligation',
        'EARLY_RETURN' => 'Return Processing', // legacy records only
        'INCIDENT_OPEN' => 'Accountability Review',
        'RECEIPT_SUBMITTED' => 'Receipt Submitted',
        'PENDING_VERIFICATION' => 'Pending Verification',
        'SUBMITTED_PENDING_ORIGINAL' => 'Pending Original Receipt',
        'RETURNED_PENDING_SETTLEMENT' => 'Pending Settlement',
        'SERVICEABLE' => 'Serviceable',
        'DAMAGED_MAINTENANCE' => 'Damaged / Maintenance',
        'CONDEMNED' => 'Condemned',
        'ALLOCATED' => 'Fully Allocated',
        'BORROWED' => 'On Custody',
        'LAUNDRY' => 'In Laundry',
        'PREPARED' => 'Prepared',
        'RELEASED_PENDING_RETURN' => 'Issued / Awaiting Return',
        'IN_LAUNDRY' => 'In Laundry',
        'INCIDENT_PENDING' => 'Accountability Review',
        'BILLING_PENDING' => 'Billing Pending',
        'SUBMITTED' => 'Submitted',
        'ISSUED' => 'Pending Payment',
        'SETTLED' => 'Paid / Verified',
        'LIFTED' => 'Lifted',
        'ACTIVE' => 'Active',
        'INACTIVE' => 'Inactive',
        'SUSPENDED' => 'Suspended',
        'RESTRICTED' => 'Restricted',
        'BORROWING_RESTRICTED' => 'Borrowing Restricted',
        'ENABLED' => 'Enabled',
        'DISABLED' => 'Disabled',
        'NOT_CONFIGURED' => 'Not configured',
        'BORROWER_ONLY' => 'Borrower',
        'SPMU_HEAD' => 'SPMU Head',
        'SPMU_OFFICER' => 'SPMU Action Officer',
        'GSU_HEAD' => 'Retired Signatory Record',
        'VPAF_HEAD' => 'Retired Signatory Record',
        'ICTU_MAINTAINER' => 'ICTU Maintainer',
        'FOR_LAUNDRY' => 'Awaiting Laundry Return',
        'IN_PROCESS' => 'Legacy Laundry Process',
        'TURNED_OVER_TO_LAUNDRY' => 'Internal Laundry Pending',
        'VERIFIED_BY_ACTION_OFFICER' => 'Verified by Action Officer',
        'READY_FOR_PICKUP' => 'Legacy Ready for Pickup',
        'READY_FOR_SPMU_RETURN' => 'Ready for SPMU Return',
        'AWAITING_FINAL_FORM_UPLOAD' => 'Awaiting Final Form Upload',
        'FORM_REPLACEMENT_REQUIRED' => 'Replacement Form Required',
        'FOR_SPMU_FINAL_CHECK' => 'Legacy SPMU Final Check',
        'LAUNDRY_COMPLETED' => 'Laundry Completed / Available',
    ];
    $display = $label ?: ($labels[$key] ?? str($value)->replace('_', ' ')->lower()->title());
    $tone = match (true) {
        str_contains($key, 'OVERDUE') || in_array($key, ['REJECTED', 'EXPIRED', 'FAILED', 'UNAVAILABLE', 'CRITICAL', 'LOST', 'DESTROYED', 'STOLEN', 'CONDEMNED'], true) => 'danger',
        str_contains($key, 'APPROVED') || str_contains($key, 'COMPLETED') || str_contains($key, 'VERIFIED') || in_array($key, ['ACTIVE', 'AVAILABLE', 'READY_FOR_RELEASE', 'RELEASED', 'RETURNED', 'SETTLED', 'EFFECTIVE', 'FINAL', 'CLOSED'], true) => 'success',
        str_contains($key, 'RETURNED_FOR_REVISION') || str_contains($key, 'DUE_SOON') || str_contains($key, 'PENDING') || str_contains($key, 'AWAITING') || str_contains($key, 'LOW_STOCK') || str_contains($key, 'OBLIGATION') || str_contains($key, 'DAMAGED') || $key === 'MISSING' => 'warning',
        str_contains($key, 'UNDER_') || str_contains($key, 'PREPARING') || in_array($key, ['INFORMATIONAL', 'INFO', 'SUBMITTED', 'UNREAD', 'RECEIVED', 'IN_PROCESS', 'TURNED_OVER_TO_LAUNDRY', 'VERIFIED_BY_ACTION_OFFICER', 'ALLOCATED', 'BORROWED', 'RELEASED_PENDING_RETURN'], true) => 'info',
        in_array($key, ['INACTIVE', 'NOT_APPLICABLE', 'NOT_CONFIGURED', 'CANCELLED', 'VOID', 'WAIVED', 'SUPERSEDED', 'INVALIDATED'], true) => 'neutral',
        default => 'neutral',
    };
@endphp

<span {{ $attributes->class(['status-badge', 'status-'.$tone])->merge(['data-status-tone' => $tone]) }}>{{ $display }}</span>
