<?php

namespace App\Services;

use App\Reports\ReportBuilder;
use App\Reports\ReportCatalogue;
use App\Reports\ReportDataset;
use App\Reports\ReportFilters;
use App\Models\User;
use Illuminate\Support\Str;

/**
 * The entry point for generating a formal report.
 *
 * Screen, CSV and print all call this one method with the same filters, so a
 * report's records are produced exactly once per format-independent query.
 * Report-specific logic lives in the builder the catalogue names; this class
 * only resolves the builder and stamps the generated-report metadata every
 * output is required to carry.
 */
class ReportService
{
    /**
     * Generate a report, or return null when the report has not yet been
     * migrated onto the dataset pipeline (the legacy controller path still
     * serves those, unchanged).
     */
    public function generate(ReportFilters $filters, ?User $generatedBy = null): ?ReportDataset
    {
        $definition = ReportCatalogue::definition($filters->reportKey);

        if ($definition['builder'] === null) {
            return null;
        }

        /** @var ReportBuilder $builder */
        $builder = app($definition['builder']);

        return $builder->build($filters)->withMeta(
            $this->metadata($filters, $definition['label'], $generatedBy)
        );
    }

    /**
     * The provenance block shown on screen, written into the CSV header, and
     * printed: what was run, over what period, with which filters, how many
     * records it returned, by whom, and when.
     *
     * @return array<string, mixed>
     */
    private function metadata(
        ReportFilters $filters,
        string $label,
        ?User $generatedBy
    ): array {
        return [
            'report_name' => $label,
            'period_label' => $this->periodLabel($filters),
            'period_selection' => $filters->periodSelection,
            'period_from' => $filters->from->toDateString(),
            'period_to' => $filters->to->toDateString(),
            'academic_period' => $filters->selectedAcademicPeriod
                ? trim(
                    $filters->selectedAcademicPeriod->academic_year
                    .' · '.$filters->selectedAcademicPeriod->term_name
                )
                : null,
            'applied_filters' => $filters->describe(),
            'rejected_filters' => $filters->rejected(),
            'generated_by' => $generatedBy?->full_name,
            'generated_at' => now()->format('d M Y, g:i A'),
        ];
    }

    private function periodLabel(ReportFilters $filters): string
    {
        return $filters->from->isSameDay($filters->to)
            ? $filters->from->format('d M Y')
            : $filters->from->format('d M Y').' – '.$filters->to->format('d M Y');
    }

    /**
     * The download filename for a generated report.
     */
    public function filename(ReportDataset $dataset): string
    {
        return 'spmu-'.Str::slug($dataset->reportKey).'-report-'
            .now()->format('Ymd-His').'.csv';
    }

    /**
     * Stream the dataset as CSV.
     *
     * The rows written here are ReportDataset::records(), the same values the
     * screen table renders, so the CSV cannot contain a different record set
     * from the report the user is looking at.
     */
    public function writeCsv(ReportDataset $dataset, mixed $handle): void
    {
        $meta = $dataset->meta;

        fputcsv($handle, [$meta['report_name'] ?? $dataset->label]);
        fputcsv($handle, ['Reporting period', $meta['period_label'] ?? '']);

        foreach (($meta['applied_filters'] ?? []) as $filterLabel => $value) {
            fputcsv($handle, [$filterLabel, $value]);
        }

        fputcsv($handle, ['Records', (string) $dataset->count()]);

        if (! empty($meta['generated_by'])) {
            fputcsv($handle, ['Generated by', $meta['generated_by']]);
        }

        fputcsv($handle, ['Generated at', $meta['generated_at'] ?? '']);
        fputcsv($handle, []);

        fputcsv($handle, $dataset->columnLabels());

        foreach ($dataset->records() as $record) {
            fputcsv($handle, $record);
        }
    }
}
