@extends('layouts.app', ['title' => 'Temporary Delegations'])
@section('content')
<section class="page-heading"><div><p class="eyebrow">ICTU controlled authority</p><h1>Temporary delegated approvers</h1><p>A delegate uses their own CSPC account. Only SPMU approval authority may be delegated in the active borrowing workflow; authority is time-bound, documented, and fully auditable.</p></div><a class="button secondary ui-pressable" href="{{ route('administration.index') }}"><x-icon name="arrow-left" size="17" /> Back</a></section>
<section class="content-grid">
    <form class="card form-grid" method="post" action="{{ route('administration.delegations.store') }}">@csrf
        <div><p class="eyebrow">New authority record</p><h2>Record a delegation</h2></div>
        <label>Approval office<select name="office_role" required><option value="">Select office</option>@foreach(['SPMU'] as $office)<option value="{{ $office }}" @selected(old('office_role')===$office)>{{ $office }}</option>@endforeach</select></label>
        <label>Unavailable Head<select name="absent_head_user_id" required><option value="">Select Head</option>@foreach($heads as $head)<option value="{{ $head->id }}" @selected(old('absent_head_user_id')==$head->id)>{{ $head->full_name }} — {{ str_replace('_',' ',$head->access_classification->value) }}</option>@endforeach</select></label>
        <label>Authorized acting officer<select name="delegate_user_id" required><option value="">Select officer</option>@foreach($officers as $officer)<option value="{{ $officer->id }}" @selected(old('delegate_user_id')==$officer->id)>{{ $officer->full_name }} — {{ $officer->organizationalUnit?->unit_code }}</option>@endforeach</select></label>
        <div class="form-columns"><label>Effective from<input type="datetime-local" name="effective_from" value="{{ old('effective_from') }}" required></label><label>Effective until<input type="datetime-local" name="effective_to" value="{{ old('effective_to') }}" required></label></div>
        <label>Written authority reference<input name="authority_reference" value="{{ old('authority_reference') }}" placeholder="Office memorandum or authority reference" required></label>
        <label>Reason<textarea name="reason" required>{{ old('reason') }}</textarea></label>
        <button class="button primary">Activate delegated authority</button>
    </form>
    <article class="card"><p class="eyebrow">Mandatory safeguards</p><h2>How delegation works</h2><div class="steps"><div class="step"><strong>Own account only</strong><small>The trusted officer never receives or opens the Head's password.</small></div><div class="step"><strong>Exact office and dates</strong><small>The system grants only the named approval authority during the recorded period.</small></div><div class="step"><strong>Attributed decision</strong><small>Every delegated SPMU decision records the acting officer and the temporary delegation.</small></div><div class="step"><strong>Immediate revocation</strong><small>ICTU can revoke unused authority without altering decisions already recorded.</small></div></div></article>
</section>
<section class="content-area"><article class="card"><div class="card-header"><div><p class="eyebrow">Authority register</p><h2>Delegation history</h2></div></div><div class="table-wrap"><table><thead><tr><th>Office / period</th><th>Head</th><th>Acting officer</th><th>Authority</th><th>Status / control</th></tr></thead><tbody>@forelse($delegations as $delegation)<tr><td><strong>{{ $delegation->office_role }}</strong><small><x-date :value="$delegation->effective_from" with-time /> to <x-date :value="$delegation->effective_to" with-time /></small></td><td>{{ $delegation->absentHead->full_name }}</td><td>{{ $delegation->delegate->full_name }}<small>Recorded by {{ $delegation->recorder->full_name }}</small></td><td>{{ $delegation->authority_reference }}<small>{{ $delegation->reason }}</small></td><td><x-status-badge :status="$delegation->isEffective() ? 'EFFECTIVE' : $delegation->status" />@if($delegation->status==='ACTIVE' && !$delegation->revoked_at)<form method="post" action="{{ route('administration.delegations.revoke',$delegation) }}" class="inline-actions top-gap">@csrf<input name="reason" placeholder="Revocation reason" required><button>Revoke</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="empty-state">No delegation has been recorded.</td></tr>@endforelse</tbody></table></div></article></section>
@endsection
