@extends('layouts.app', ['title' => $item->exists ? 'Edit Inventory Item' : 'Add Inventory Item'])
@section('content')
<section class="page-heading"><div><p class="eyebrow">SPMU inventory administration</p><h1>{{ $item->exists ? 'Edit inventory item' : 'Add inventory item' }}</h1></div><a class="button ghost" href="{{ route('inventory.index') }}">Back to inventory</a></section>
<section class="content-area narrow"><form method="post" action="{{ $item->exists ? route('inventory.update', $item) : route('inventory.store') }}" class="card form-grid">@csrf @if($item->exists)@method('PUT')@endif
    <div class="form-columns"><label>Category<select name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $item->category_id)==$category->id)>{{ $category->category_name }}</option>@endforeach</select></label><label>Unit<select name="unit_id" required>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected(old('unit_id', $item->unit_id)==$unit->id)>{{ $unit->unit_name }}</option>@endforeach</select></label></div>
    <label>Unique description<input name="unique_description" value="{{ old('unique_description', $item->unique_description) }}" required></label>
    <label>Specification<textarea name="specification">{{ old('specification', $item->specification) }}</textarea></label>
    <div class="form-columns"><label>Total quantity<input type="number" step="1" min="0" inputmode="numeric" name="total_quantity" value="{{ old('total_quantity', $item->total_quantity ?? 0) }}" required></label><label>Condition<select name="condition_code"><option value="SERVICEABLE" @selected(old('condition_code',$item->condition_code)==='SERVICEABLE')>Serviceable</option><option value="DAMAGED_MAINTENANCE" @selected(old('condition_code',$item->condition_code)==='DAMAGED_MAINTENANCE')>Damaged / Maintenance</option><option value="CONDEMNED" @selected(old('condition_code',$item->condition_code)==='CONDEMNED')>Condemned</option></select></label></div>
    <fieldset><legend>Operational flags</legend><div class="check-grid"><label><input type="checkbox" name="borrowable" value="1" @checked(old('borrowable', $item->exists ? $item->borrowable : true))> Borrowable</label><label><input type="checkbox" name="laundry_required" value="1" @checked(old('laundry_required', $item->laundry_required))> Laundry required</label><label><input type="checkbox" name="off_campus_allowed" value="1" @checked(old('off_campus_allowed', $item->off_campus_allowed))> Off-campus allowed (Barricade only)</label><label><input type="checkbox" name="provisional" value="1" @checked(old('provisional', $item->provisional))> Provisional</label><label><input type="checkbox" name="active" value="1" @checked(old('active', $item->exists ? $item->active : true))> Active</label></div></fieldset>
    <label>Mandatory change reason<textarea name="change_reason" required>{{ old('change_reason') }}</textarea></label>
    <div class="actions"><button class="button primary ui-pressable">Save inventory item</button><a class="button secondary ui-pressable" href="{{ route('inventory.index') }}">Cancel</a></div>
</form></section>
@endsection
