@extends('layouts.app', ['title' => $dataset->label])

@section('content')
@php
    /*
    | The printable copy.
    |
    | It renders the whole record set from the same ReportService call the
    | screen used, so a printed report is never one page of a larger result.
    | Application chrome is hidden by the print stylesheet below.
    */
    $meta = $dataset->meta;
    $appliedFilters = $meta['applied_filters'] ?? [];
@endphp

<style>
/* On paper only the report exists. */
@media print {
    .app-sidebar, .app-topbar, .sidebar-brand-row, .report-print-actions { display: none !important; }
    .app-shell, .app-main, .app-content { display: block !important; margin: 0 !important; padding: 0 !important; }
    body { background: #fff !important; }
    .report-print-sheet { box-shadow: none !important; border: 0 !important; padding: 0 !important; }
    .report-print-table thead { display: table-header-group; }
    .report-print-table tr { break-inside: avoid; }
}

.report-print-sheet { max-width: 1100px; margin: 0 auto; padding: 26px 28px; background: #fff; border: 1px solid var(--border); border-radius: var(--radius); }
.report-print-masthead { text-align: center; padding-bottom: 14px; border-bottom: 2px solid var(--border-strong); }
.report-print-masthead strong { display: block; font-size: 15px; color: var(--heading); letter-spacing: .02em; }
.report-print-masthead span { display: block; margin-top: 2px; font-size: 11.5px; color: var(--text-muted); }
.report-print-title { margin: 18px 0 4px; font-size: 17px; color: var(--heading); }
.report-print-period { margin: 0 0 16px; color: var(--text-secondary); font-size: 12.5px; }
.report-print-meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px 18px; margin: 0 0 18px; padding: 12px 14px; border: 1px solid var(--border); border-radius: 8px; }
.report-print-meta dt { font-size: 10px; font-weight: 800; letter-spacing: .06em; text-transform: uppercase; color: var(--text-muted); }
.report-print-meta dd { margin: 3px 0 0; font-size: 12px; color: var(--text); }
.report-print-table { width: 100%; border-collapse: collapse; font-size: 11px; }
.report-print-table th { padding: 7px 8px; text-align: left; border-bottom: 1.5px solid var(--border-strong); color: var(--heading); font-size: 9.5px; font-weight: 800; letter-spacing: .05em; text-transform: uppercase; }
.report-print-table td { padding: 6px 8px; border-bottom: 1px solid var(--row-border); color: var(--text); vertical-align: top; }
.report-print-table td.numeric, .report-print-table th.numeric { text-align: right; font-variant-numeric: tabular-nums; }
.report-print-actions { display: flex; justify-content: flex-end; gap: 10px; max-width: 1100px; margin: 0 auto 12px; }
.report-print-empty { padding: 24px; text-align: center; color: var(--text-muted); }
.report-print-footer { margin-top: 16px; padding-top: 10px; border-top: 1px solid var(--border); color: var(--text-muted); font-size: 10.5px; }
</style>

<div class="report-print-actions">
    <button class="button primary ui-pressable" type="button" onclick="window.print()">
        <x-icon name="printer" size="16" />
        Print
    </button>
</div>

<article class="report-print-sheet">
    <header class="report-print-masthead">
        <strong>Supply and Property Management Unit</strong>
        <span>Asset Custody Monitoring Program · Camarines Sur Polytechnic Colleges</span>
    </header>

    <h1 class="report-print-title">{{ $dataset->label }}</h1>
    <p class="report-print-period">{{ $meta['period_label'] ?? '' }}</p>

    <dl class="report-print-meta">
        <div>
            <dt>Records Found</dt>
            <dd>{{ number_format($dataset->count()) }}</dd>
        </div>
        <div>
            <dt>Applied Filters</dt>
            <dd>{{ ! empty($appliedFilters) ? implode(' • ', array_values($appliedFilters)) : 'None' }}</dd>
        </div>
        <div>
            <dt>Generated By</dt>
            <dd>{{ $meta['generated_by'] ?: 'Not recorded' }}</dd>
        </div>
        <div>
            <dt>Generated On</dt>
            <dd>{{ $meta['generated_at'] ?? '' }}</dd>
        </div>
    </dl>

    @if($dataset->isEmpty())
        <p class="report-print-empty">
            {{ App\Reports\ReportCatalogue::emptyMessage($dataset->reportKey) }}
        </p>
    @else
        <table class="report-print-table">
            <thead>
                <tr>
                    @foreach($dataset->columns as $column)
                        <th @class(['numeric' => ($column['align'] ?? null) === 'numeric'])>{{ $column['label'] }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($dataset->rows as $row)
                    <tr>
                        @foreach($dataset->columns as $column)
                            <td @class(['numeric' => ($column['align'] ?? null) === 'numeric'])>{{ $row[$column['key']] ?? '' }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @php
        $printFooter = 'Based on official operational records. '
            .number_format($dataset->count())
            .' '.($dataset->count() === 1 ? 'record' : 'records').' in this report.';
    @endphp

    <p class="report-print-footer">{{ $printFooter }}</p>
</article>
@endsection
