@php
    /*
    | Provenance for the generated report.
    |
    | A reader must be able to answer, without scrolling: what report, over
    | what period, under which filters, how many records, generated by whom,
    | and when. The same block is written into the CSV header and printed.
    */
    $meta = $dataset->meta;
    $appliedFilters = $meta['applied_filters'] ?? [];
@endphp

<dl class="report-metadata" aria-label="Generated report details">
    <div class="report-metadata-count">
        <dt>Records Found</dt>
        <dd><strong>{{ number_format($dataset->count()) }}</strong></dd>
    </div>

    <div>
        <dt>Applied Filters</dt>
        <dd>
            @if(! empty($appliedFilters))
                {{ implode(' • ', array_values($appliedFilters)) }}
            @else
                None
            @endif
        </dd>
    </div>

    <div>
        <dt>Generated By</dt>
        <dd>{{ $meta['generated_by'] ?: 'Not recorded' }}</dd>
    </div>

    <div>
        <dt>Generated On</dt>
        <dd>{{ $meta['generated_at'] ?? '' }}</dd>
    </div>
</dl>

@if(! empty($meta['rejected_filters']))
    <p class="report-filter-warning" role="status">
        <x-icon name="warning" size="16" />
        <span>
            These filters were not recognised and were ignored:
            {{ implode(', ', array_keys($meta['rejected_filters'])) }}.
        </span>
    </p>
@endif
